version: "3.6"

services:
  poa:
    build:
      context: .

  parity:
    image: appliedblockchain/parity-solo-instant
    ports:
      - 8545:8545
    volumes:
      - parity:/solo/chains

volumes:
  parity:
